#!/bin/sh

# Made by Banbeucmas
# Dotfiles: https://github.com/Banbeucmas/banbeucmas-dotfiles

initializeANSI()
{
  esc=""
 
  blackf="${esc}[38;5;232m";   redf="${esc}[38;5;196m";    greenf="${esc}[32m"
  yellowf="${esc}[33m"   bluef="${esc}[34m";   purplef="${esc}[38;5;216m"
  brownf="${esc}[38;5;130m";    whitef="${esc}[37m"; humanf="${esc}[38;5;223m"
 
  redt="${esc}[31m";

  blackb="${esc}[38;5;241m";   redb="${esc}[41m";    greenb="${esc}[42m"
  yellowb="${esc}[43m"   blueb="${esc}[44m";   purpleb="${esc}[45m"
  brownb="${esc}[38;5;214m";    whiteb="${esc}[47m"; humanb="${esc}[38;5;229m"
 
  boldon="${esc}[1m";    boldoff="${esc}[22m"
  italicson="${esc}[3m"; italicsoff="${esc}[23m"
  ulon="${esc}[4m";      uloff="${esc}[24m"
  invon="${esc}[7m";     invoff="${esc}[27m"
 
  reset="${esc}[0m"
}

initializeBars(){
  f=3 b=4
  for j in f b; do
    for i in {0..7}; do
      printf -v $j$i %b "\e[${!j}${i}m"
    done
  done
  bld=$'\e[1m'
  rst=$'\e[0m'
  inv=$'\e[7m'
}

initializeANSI
initializeBars

cat << EOF
${reset}                                ${blackf}██████████████████
${reset}  ${blackf}██████████████████████    ████${reset}${redf}████████████${reset}${whitef}██${reset}${redf}██${reset}${whitef}██${reset}${blackf}██
${reset}  ${blackf}██${reset}${whitef}██${reset}${redf}██${reset}${whitef}██${reset}${redf}██████████${reset}${blackf}████████████████████${reset}${redf}██${reset}${whiteb}██${reset}${redf}████${reset}${whiteb}██${reset}${blackf}██
${reset}  ${blackf}██${reset}${whiteb}██${reset}${redf}████${reset}${whitef}██${reset}${redf}████${reset}${blackf}████████████${reset}${blackb}██████████${reset}${blackf}██████${reset}${redf}██${reset}${whiteb}██${reset}${blackf}██
${reset}    ${blackf}██${reset}${whitef}██${reset}${redf}██${reset}${whiteb}██${reset}${redf}██${reset}${blackf}██████${reset}${blackb}██████████████████████${reset}${blackf}████${reset}${whiteb}██${reset}${blackf}██
${reset}    ${blackf}██${reset}${whiteb}██${reset}${redf}████${reset}${blackf}██████${reset}${blackb}██████████████████████████${reset}${blackf}████
${reset}      ${blackf}██${reset}${whiteb}██${reset}${blackf}██████${reset}${blackb}██████████████████████████████${reset}${blackf}████
${reset}      ${blackf}████████${reset}${blackb}██████████████████████████████████${reset}${blackf}████
${reset}      ${blackf}████████${reset}${blackb}████████████████████████████████${reset}${whiteb}██${reset}${blackb}██${reset}${blackf}██
${reset}    ${blackf}██${reset}${blackb}██${reset}${blackf}██████${reset}${blackb}████████████████████████${reset}${blackf}██${reset}${whiteb}██████${reset}${blackb}████${reset}${blackf}████
${reset}    ${blackf}██${reset}${blackb}████${reset}${blackf}██${reset}${blackb}██████${reset}${blackf}██${reset}${whiteb}████████${reset}${blackb}██${reset}${whiteb}██████${reset}${blackb}██${reset}${blackf}██${reset}${blackb}████████████${reset}${blackf}██
${reset}    ${blackf}██${reset}${blackb}████${reset}${blackf}██${reset}${blackb}████${reset}${blackf}██${reset}${blackb}██████████${reset}${blackf}██${reset}${blackb}██████${reset}${blackf}████${reset}${blackb}██████${reset}${blackf}██${reset}${blackb}████${reset}${blackf}██
${reset}    ${blackf}██${reset}${blackb}████${reset}${blackf}██${reset}${blackb}██${reset}${blackf}██${reset}${blackb}██████████${reset}${blackf}████${reset}${blackb}████${reset}${blackf}██████${reset}${blackb}██${reset}${blackf}██${reset}${blackb}██${reset}${blackf}████${reset}${blackb}██${reset}${blackf}██
${reset}    ${blackf}██${reset}${blackb}████████${reset}${blackf}██${reset}${blackb}████████${reset}${blackf}██████${reset}${blackb}██${reset}${blackf}████${reset}${purplef}██${reset}${blackf}██████${reset}${blackb}██${reset}${blackf}████████
${reset}      ${blackf}██${reset}${blackb}██████████${reset}${blackf}████████████████${reset}${purplef}██${reset}${humanf}██${reset}${blackf}██${reset}${humanf}██${reset}${blackf}██████████
${reset}      ${blackf}██${reset}${blackb}████${reset}${blackf}██${reset}${blackb}██████${reset}${blackf}██${reset}${humanf}██${reset}${blackf}████${reset}${purplef}██${reset}${blackf}██${reset}${purplef}██${reset}${humanf}████${reset}${brownf}██${reset}${humanb}██${reset}${redf}██${reset}${blackf}████${reset}  ${blackf}██
${reset}      ${blackf}██${reset}${blackb}████${reset}${blackf}██████${reset}${redf}████${reset}${humanb}████${reset}${brownf}██${reset}${humanf}██${reset}${purplef}██${reset}${humanf}██████${reset}${brownb}██${reset}${humanb}██${reset}${whitef}██${reset}${blackf}██
${reset}      ${blackf}██${reset}${blackb}████${reset}${blackf}██████${reset}${whitef}████${reset}${humanb}██${reset}${brownf}██${reset}${brownb}██${reset}${humanf}██████████${reset}${brownf}██${reset}${humanb}██${reset}${redf}██${reset}${blackf}██
${reset}      ${blackf}██${reset}${blackb}██${reset}${blackf}████████${reset}${redf}████${reset}${boldon}${whitef}██${reset}${brownf}████${reset}${humanf}████████████${reset}${purplef}██${reset}${humanf}██${reset}${blackf}██
${reset}    ${blackf}████${reset}${blackb}██${reset}${blackf}████████${reset}${humanb}██${reset}${humanf}██${reset}${purplef}██${reset}${humanf}██████████████${reset}${purplef}██${reset}${blackf}██${reset}${blackb}██${reset}${blackf}██              
${reset}    ${blackf}██████████${reset}${blackb}██${reset}${blackf}████${reset}${blackb}██${reset}${blackf}██${reset}${purplef}██████████████${reset}${blackf}██${reset}${blackb}██${reset}${blackf}██
${reset}    ${blackf}████████${reset}  ${blackf}██${reset}${blackb}██${reset}${blackf}██${reset}${blackb}██${reset}${purplef}████${reset}${redf}██${reset}${humanf}██████${reset}${yellowf}██${reset}${humanf}██${reset}${purplef}██${reset}${blackf}██
${reset}      ${blackf}██████${reset}  ${blackf}██${reset}${blackb}██${reset}${blackf}██${reset}${whiteb}██${reset}${humanf}██${reset}${redf}████████${reset}${yellowf}██${reset}${boldon}${yellowf}██${reset}${yellowf}██${reset}${blackf}██${reset}${whiteb}██${reset}${blackf}██
${reset}      ${blackf}████${reset}      ${blackf}██${reset}${whiteb}██${reset}${whitef}██${reset}${whiteb}██${reset}${redf}████████${reset}${boldon}${yellowf}██████${reset}${blackf}██${reset}${whiteb}██${reset}${blackf}██
${reset}      ${blackf}██${reset}        ${blackf}██${reset}${whiteb}██${reset}${whitef}████${reset}${blackf}██${reset}${redf}██████████████${reset}${blackf}██${reset}${whiteb}██${reset}${blackf}██
${reset}              ${blackf}██${reset}${whiteb}██${reset}${redf}██${reset}${whitef}████${reset}${blackf}██${reset}${redf}████████████████${reset}${blackf}██${reset}${blackf}██
${reset}              ${blackf}██${reset}${whiteb}██${reset}${whitef}██${reset}${redf}██${reset}${whitef}██${reset}${blackf}██${reset}${redf}██████████████████${reset}${blackf}██
${reset}              ${blackf}██${reset}${redf}██${reset}${whiteb}██${reset}${whitef}██${reset}${whiteb}██${reset}${redf}██████████████████${reset}${whiteb}██${reset}${blackf}██
${reset}              ${blackf}██${reset}${whiteb}██${reset}${redf}████████████████████${reset}${whiteb}████${reset}${blackf}██
${reset}                ${blackf}██${reset}${redf}██${reset}${whiteb}████${reset}${whitef}██${reset}${redf}████${reset}${whitef}████${reset}${blackf}████${reset}${blackb}██${reset}${blackf}██
${reset}                  ${blackf}██████${reset}${blackb}██${reset}${blackf}████████${reset}  ${blackf}████

EOF
