#!/bin/bash

rsync -P -r --exclude 'chromium' --exclude 'discord'  ~/.config/ /mnt/Workspace/Dotfiles/.config
rsync -P ~/.zshrc /mnt/Workspace/Dotfiles
rsync -P ~/.vimrc /mnt/Workspace/Dotfiles
rsync -P ~/.Xresources /mnt/Workspace/Dotfiles
rsync -P -r ~/.toys /mnt/Workspace/Dotfiles
rsync -P -r ~/.scripts /mnt/Workspace/Dotfiles
rsync -P -r ~/Pictures/Wallpapers /mnt/Workspace/Dotfiles/
rsync -P -r ~/.IntelliJIdea2018.3/config/codestyles /mnt/Workspace/Dotfiles/.IntelliJIdea2018.3/config/codestyles 
rsync -P -r ~/.IntelliJIdea2018.3/config/options /mnt/Workspace/Dotfiles/.IntelliJIdea2018.3/config/options
rsync -P -r ~/.WebStorm2018.3/config/codestyles /mnt/Workspace/Dotfiles/.WebStorm2018.3/config/codestyles
rsync -P -r ~/.WebStorm2018.3/config/options /mnt/Workspace/Dotfiles/.WebStorm2018.3/config/options

