#!/bin/bash

killall xst

bspc rule -a xst-256color:xst-neofetch state=floating
bspc rule -a xst-256color:xst-panes state=floating
bspc rule -a xst-256color:xst-ttyclock state=floating

xst -n xst-neofetch -g 60x13 -e zsh -c 'neofetch && xdo move -n xst-neofetch -x 12 -y 53 & sleep 30' &
xst -n xst-panes -g 43x5 -e zsh -c '~/.toys/panes && xdo move -n xst-panes -x 1007 -y 53 & sleep 30' &
xst -n xst-ttyclock -g 52x11 -e zsh -c 'xdo move -n xst-ttyclock -x 12 -y 509 && tty-clock -c -C 5 & sleep 30 && exit 0' &&

xst
