#!/bin/bash

killall xst

bspc rule -a xst-256color:xst-neofetch state=floating
bspc rule -a xst-256color:xst-panes state=floating
bspc rule -a xst-256color:xst-ttyclock state=floating

xst -n xst-neofetch -g 60x13 -e zsh -c 'neofetch && xdo move -n xst-neofetch -x 12 -y 53 & sleep 30' &
xst -n xst-ncmpcpp -g 61x18 -e zsh -c 'xdo move -n xst-ncmpcpp -x 12 -y 499 && ncmpcpp' &
xst -n xst-ttyclock -g 47x11 -e zsh -c 'xdo move -n xst-ttyclock -x 998 -y 53 && tty-clock -c -C 1 & sleep 30 && exit 0' &&

xst & killall ncmpcpp
