#!/bin/sh

if [ "$1" == "-h" ]; then
    echo "COMMAND: toys [OPTIONS] [SCRIPTS]"
    echo ""
    echo "-h        Display this page"
    echo "-l        List all avaliable scripts" 
    exit 0
elif [ "$1" == "-l" ]; then
    ls ~/.toys
    exit 0
fi


if [ ! -f ~/.toys/$1 ]; then
    echo "Toy script doesn't excist" 
else
    clear
    ~/.toys/$1
fi
    
